### PR TITLE
Fix for context didisave notification broadcast

### PR DESCRIPTION
**Pull request by IvanKalaica**
test plan: all tests passing

### CODE REVIEW

**Review by ifabijanovic — APPROVED** [review]

**Comment by ifabijanovic** [comment]
Currently we use an older version of RestKit, this will be merged into a branch targeting that older version right?

**Comment by ifabijanovic** [comment]
How will this fix affect iOS 9 and iOS 8 users?

**Comment by IvanKalaica** [comment]
Yes, I created branch from v0.25.0 tag and named it master-bellabeat

**Comment by IvanKalaica** [comment]
Nothing changed for iOS9 and iOS8 users. We are now simply getting values for explicit key's when fetching objectID's.

**Pull request closed without merging**
